spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/project
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    jdbc-url: jdbc:mysql://localhost:3306/project?autoReconnectForPools=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#mybatis
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.soft.eva.domain
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


